import smtplib
import random
import datetime
import os
import re
import threading
import uuid
from email.mime.text import MIMEText
import logging
from Backend.BusinessLayer.User.User import User  # Adjusted import
from Backend.BusinessLayer.Util.Exceptions import *
from Backend.DataLayer.User.UserRepository import UserRepository  # Import the SQLAlchemy repository


class UserFacade:
    _instance = None  # Singleton pattern

    def __new__(cls, *args, **kwargs):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        if not hasattr(self, '_initialized'):
            self.user_repo = UserRepository()  # Create repository instance
            self.pending_auth_codes = {}  # Stores pending auth codes and their expiry times
            self.auth_lock = threading.Lock()  # Lock for thread-safe access
            self._initialized = True

    def generateUserId(self):
        """
        Generate a unique user ID (though with SQLAlchemy,
        the ID will be auto-generated by the database)
        """
        return str(uuid.uuid4())

    def register(self, email, password, first_name, last_name):
        """
        Unified register function with database integration
        """
        # Validate inputs
        if not self.is_valid_name(first_name):
            raise Exception("השם הפרטי אינו תקין.")

        if not self.is_valid_name(last_name):
            raise Exception("שם המשפחה אינו תקין.")

        if not self.is_valid_email(email):
            raise Exception("האימייל אינו תקין.")

        if not self.is_valid_password(password):
            raise Exception("הסיסמה אינה תקינה.")

        # Check if user already exists
        existing_user = self.user_repo.get_user_by_email(email)
        if existing_user:
            raise Exception("המשתמש כבר קיים במערכת.")

        # Send authentication code
        self.send_auth_code(email, first_name)
        return {"message": f"קוד אימות נשלח למייל {email}"}

    def register_authentication_part(self, email, auth_code: str):
        """
        Verify authentication code
        """
        try:
            stored_code, expiry_time = self.pending_auth_codes[email]
            if auth_code == stored_code:
                if datetime.datetime.now() <= expiry_time:
                    return {"message": "עוברים למעבר על תנאי השימוש"}
                else:
                    logging.error("Authentication failed. The code has expired.")
                    raise Exception("אימות נכשל. הקוד פג תוקף.")
            else:
                logging.error("Incorrect authentication code.")
                raise Exception("קוד אימות שגוי.")
        except Exception as e:
            logging.error(f"Attempt failed: {e}")
            raise Exception("האימות נכשל. הרשמה בוטלה.")

    def register_termOfUse_part(self, email, password, first_name, last_name):
        """
        Complete user registration and save to database


        """
        user_id = self.generateUserId()
        try:
            # Create user and save to database
            user = User.create(
                user_id=user_id,
                email=email,
                password=password,
                first_name=first_name,
                last_name=last_name
            )

            logging.info(f"User {first_name} {last_name} registered successfully.")
            return user.user_id, {"message": f"User {first_name} {last_name} registered successfully."}
        except Exception as e:
            logging.error(f"Registration failed: {e}")
            raise Exception("האישור נכשל. הרשמה בוטלה.")

    def get_user_courses(self, user_id):
        """
        Retrieve user courses from database
        """
        user = self.user_repo.get_user_by_id(user_id)
        return user.courses if user else []

    def login(self, email, password):
        """
        Authenticate user using database
        """
        user = self.user_repo.get_user_by_email(email)

        if user is None:
            raise UserOrPasswordIncorrectError()

        if user.password != password:
            raise UserOrPasswordIncorrectError()

        # Update login status
        user.login()

        logging.info(f"Login successful for user: {email}")
        message = "התחברות בוצעה בהצלחה"
        return user.id, {"message": message}

    def logout(self, email):
        """
        Logout user and update database
        """
        user = self.user_repo.get_user_by_email(email)

        if user is None:
            raise UserOrPasswordIncorrectError()

        if not user.loggedIn:
            raise UserIsNotLoggedInError(email)

        user.logout()

        logging.info(f"User {email} logged out successfully.")
        message = "התנתקות בוצעה בהצלחה"
        return message

    def registerToCourse(self, courseId, userId):
        """
        Register user to a course and update database
        """
        user = self.user_repo.get_user_by_id(userId)
        if user:
            user.registerToCourse(courseId)
        else:
            raise UserDoesnotExistsError(userId)

    def editUserProfile(self, email, **kwargs):
        """
        Edit user profile and update database
        """
        user = self.user_repo.get_user_by_email(email)
        if user:
            user.editProfile(**kwargs)
            return "Profile updated successfully"
        else:
            raise UserDoesnotExistsError()

    def getUser(self, user_id):
        """
        Retrieve user by ID from database
        """
        return self.user_repo.get_user_by_id(user_id)

    def registerWithoutAuth(self, email, password, first_name, last_name):
        """
        Register user without authentication steps
        """
        # Validate inputs
        if not self.is_valid_name(first_name):
            raise Exception("השם הפרטי אינו תקין.")

        if not self.is_valid_name(last_name):
            raise Exception("שם המשפחה אינו תקין.")

        if not self.is_valid_email(email):
            raise Exception("האימייל אינו תקין.")

        if not self.is_valid_password(password):
            raise Exception("הסיסמה אינה תקינה.")

        # Check if user already exists
        existing_user = self.user_repo.get_user_by_email(email)
        if existing_user:
            raise Exception("המשתמש כבר קיים במערכת.")

        # Create user and save to database
        user = User.create(
            user_id=self.generateUserId(),
            email=email,
            password=password,
            first_name=first_name,
            last_name=last_name
        )


        logging.info(f"User {first_name} {last_name} registered successfully.")
        return user.user_id, {"message": f"User {first_name} {last_name} registered successfully."}

    # Existing validation methods remain the same
    def is_valid_email(self, email):
        """Validate email domain."""
        return bool(re.match(r".+@(post\.bgu\.ac\.il|bgu\.ac\.il)$", email))

    def is_valid_name(self, name):
        """
        Validates a name to ensure it contains only Hebrew characters, spaces, tabs, and hyphens.
        """
        hebrew_name_regex = r'^[\u0590-\u05FF]+([\s\t-][\u0590-\u05FF]+)*$'
        return bool(re.match(hebrew_name_regex, name))

    def is_valid_password(self, password):
        """
        Validate the password.
        """
        # Check for minimum and maximum length
        if len(password) < 8 or len(password) > 20:
            return False

        # Ensure password contains only allowed characters
        if not re.match(r"^[A-Za-z0-9{}\[\]!@\$%\^&\*\(\)\+]+$", password):
            return False

        # Regular expressions for each condition
        has_uppercase = re.search(r"[A-Z]", password)
        has_lowercase = re.search(r"[a-z]", password)
        has_number = re.search(r"[0-9]", password)
        has_special = re.search(r"[{}\[\]!@\$%\^&\*\(\)\+]", password)

        # Return True only if all conditions are met
        return bool(has_uppercase and has_lowercase and has_number and has_special)

    def send_auth_code(self, email, first_name):
        """Generate and send an authentication code via email."""
        auth_code = random.randint(100000, 999999)
        auth_code = str(auth_code)
        auth_code_expiry = datetime.datetime.now() + datetime.timedelta(minutes=3)
        self.pending_auth_codes[email] = (auth_code, auth_code_expiry)

        sender_email = os.getenv("EMAIL_ADDRESS")
        sender_password = os.getenv("EMAIL_PASSWORD")
        smtp_server = "smtp.gmail.com"
        smtp_port = 587

        subject = "קוד האימות שלך"
        message = (f"שלום {first_name},\n\n"
                   f"קוד האימות שלך עבור NegevNerds הוא: {auth_code}\n"
                   f"הקוד תקף למשך 3 דקות.\n\n"
                   f"תודה רבה!")
        msg = MIMEText(message)
        msg["Subject"] = subject
        msg["From"] = sender_email
        msg["To"] = email

        try:
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.send_message(msg)
            logging.info(f"Authentication code sent to {email}")
        except Exception as e:
            logging.error(f"Failed to send authentication code: {e}")
            raise Exception("Failed to send authentication code.")